name: h2g-vis
channels:
  - conda-forge
  - bioconda
dependencies:
  - pypsa>=1.0.7
  - snakemake-minimal<8
  - jupyterlab
  - plotly==6.2
  - streamlit
  - pip:
    - kaleido==0.1.0post1 # for image export with plotly on windows
    # - kaleido # for image export with plotly on linux

